In [2]:
import pandas as pd
import os

In [80]:
dict_ranks = dict()
dict_num_sp = dict()

for file in os.listdir(os.path.join(os.getcwd(), 'SampledGenomes')):
    if ".csv" in file:
        Dir = os.path.join(os.getcwd(), 'SampledGenomes', file) 
        # print(Dir)
        df = pd.read_csv(Dir)
        ranks = [ 'superkingdom', 'phylum',
           'class', 'order', 'family', 'genus', 'species']


        for i, rank in enumerate(ranks):
            if len(df[rank].unique()) > 2:
                rank_below = rank
                rank = ranks[i-1]
                break
            else:
                continue
                
        number_of_sp = []
        for i in df[rank_below]:
            number_of_sp.append(len(df[df[rank_below] == i]["species"]))
        dict_ranks[file.replace("Sampled", "").replace(".csv", "")] = [len(df[rank_below].unique()),max(number_of_sp)]
        # dict_num_sp[file.replace("Sampled", "").replace(".csv", "")] = 
#

In [89]:
pd.DataFrame.from_dict(dict_ranks).T.rename(columns = dict(zip([0, 1], ["unique_taxa_in_rank_below", "max_sp_per_rank_below"]))).sort_index()

                         unique_taxa_in_rank_below  max_sp_per_rank_below
AcetobacterDB_1                                 11                      1
ActinobacteriaDB                                 6                      7
ActinobacteriaDB_1                               6                      2
ActinobacteriaDB_2                               6                      7
AlphaproteobacteriaDB_1                         12                      2
AlphaproteobacteriaDB_2                         12                      5
AlphaproteobacteriaDB_4                         13                      5
BacteriaDB_1                                    35                      9
BacteriaDB_2                                    34                      7
BacteriaDB_3                                    34                      7
BacteriaGenomesDB                               35                      9
BacteroidetesDB                                  6                      2
BacteroidetesDB_1                                6                      1
BacteroidetesDB_2                                6                      2
BartonellaDB_1                                  24                      1
BetaproteobacteriaDB_1                           5                      2
BetaproteobacteriaDB_2                           5                      4
BrevundimonasDB_1                                7                      1
ChloroflexiDB                                    8                      2
ChloroflexiDB_1                                  8                      1
ChloroflexiDB_2                                  8                      2
DeltaproteobacteriaDB_1                          7                      4
DeltaproteobacteriaDB_2                          7                      4
FirmicutesDB                                     6                      4
FirmicutesDB_1                                   6                      2
FirmicutesDB_2                                   6                      4
GammaproteobacteriaDB_1                         19                      3
GammaproteobacteriaDB_2                         19                      4
ParacoccusDB_1                                  20                      1
Parracoccus_PPDB_1                              21                      1
ProteobacteriaDB_1                               9                      5
ProteobacteriaDB_2                               9                      9
ProteobacteriaDB_3                               9                     10
PseudomonasDB_1                                 51                      1
PseudomonasDB_2                                 51                      1
PseudomonasDB_3                                 51                      1
PseudomonasDB_4                                 51                      1
RhizobiumDB_1                                   15                      1
RickettsiaDB_1                                  16                      1
SphingomonasDB_1                                26                      1